### ISSUE TITLE
Support for RAML 1.0?

### ISSUE THREAD

**Issue by oshalygin** [jlandersen/vscode-raml#3]
Would love to help, let me know if you're already on it 👍

**Comment by jlandersen** [comment]
Hi

This builds on mulesoft's own Sublime text plugin (https://github.com/mulesoft/raml-sublime-plugin). It is based on their version 2.0.0, and unfortunately they haven't updated it since December 2015. I am keeping an eye on it and hope they will update it soon to be fully 1.0 compatible (even though they write that 2.0.0 is).

**Comment by oshalygin** [comment]
Awesome much appreciated @jlandersen !

**Comment by sichvoge** [comment]
Hi @jlandersen I will make sure they know! Please let me know if there are things currently not supported.
